#!/usr/bin/env python3
"""Print a Harbor rerun command that skips prior successful positive-reward tasks."""

from __future__ import annotations

import argparse
import json
import shlex
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SUMMARY = ROOT / "jobs" / "2026-06-15__17-20-19" / "diagnostics_status_summary.json"
DEFAULT_DATASET = ROOT / "harbor_datasets" / "wannier_200"


def material_from_record(record: dict[str, Any]) -> str:
    material = record.get("material")
    if isinstance(material, str) and material:
        return material

    subfolder = record.get("subfolder")
    if isinstance(subfolder, str) and subfolder:
        return subfolder.split("__", 1)[0]

    raise ValueError(f"Cannot determine material for record: {record!r}")


def is_positive_reward_success(record: dict[str, Any]) -> bool:
    if record.get("status") != "success":
        return False

    reward = record.get("reward", 0.0)
    try:
        return float(reward) > 0.0
    except (TypeError, ValueError):
        return False


def relpath_for_command(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(Path.cwd().resolve()))
    except ValueError:
        return str(path)


def safe_name(value: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in value)


def filtered_dataset_dir(args: argparse.Namespace, run_materials: list[str]) -> Path:
    summary_job = args.summary.parent.name
    mode = "previous_only" if args.previous_only else "pending"
    return args.dataset.parent / f"{args.dataset.name}__{mode}_{safe_name(summary_job)}_{len(run_materials)}"


def materialize_filtered_dataset(source_dataset: Path, target_dataset: Path, run_materials: list[str]) -> None:
    target_dataset.mkdir(parents=True, exist_ok=True)

    wanted = set(run_materials)
    for path in list(target_dataset.iterdir()):
        if path.name == "README.md":
            continue
        if path.name not in wanted and path.is_symlink():
            path.unlink()
        elif path.name not in wanted:
            raise SystemExit(
                f"Refusing to remove non-symlink path in generated dataset: {path}. "
                "Choose a different --filtered-dataset-dir."
            )

    for material in run_materials:
        source = source_dataset / material
        target = target_dataset / material
        if not source.is_dir():
            raise SystemExit(f"missing source task directory: {source}")
        if target.exists() or target.is_symlink():
            if target.is_symlink() and target.resolve() == source.resolve():
                continue
            raise SystemExit(
                f"Refusing to overwrite existing generated dataset entry: {target}. "
                "Choose a different --filtered-dataset-dir."
            )
        target.symlink_to(source.resolve(), target_is_directory=True)

    readme = target_dataset / "README.md"
    readme.write_text(
        "# Filtered Wannier 200 Harbor Dataset\n\n"
        f"Source dataset: `{source_dataset}`\n"
        f"Task count: {len(run_materials)}\n\n"
        "Generated by `scripts/generate_harbor_rerun_command.py`.\n",
        encoding="utf-8",
    )


def build_command(args: argparse.Namespace, dataset: Path) -> list[str]:
    command = [
        "harbor",
        "run",
        "-p",
        relpath_for_command(dataset),
        "-a",
        args.agent,
        "-m",
        args.model,
    ]

    if args.extra_arg:
        command.extend(args.extra_arg)

    return command


def dataset_materials(dataset: Path) -> list[str]:
    return sorted(path.name for path in dataset.iterdir() if path.is_dir())


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Read diagnostics_status_summary.json and print a Harbor command that "
            "does not rerun tasks with status 'success' and reward > 0.0."
        )
    )
    parser.add_argument("--summary", type=Path, default=DEFAULT_SUMMARY)
    parser.add_argument("--dataset", "-p", type=Path, default=DEFAULT_DATASET)
    parser.add_argument("--agent", "-a", default="gemini-cli")
    parser.add_argument("--model", "-m", default="google/gemini-3.1-pro-preview")
    parser.add_argument(
        "--previous-only",
        action="store_true",
        help="Run only previously attempted tasks that were not positive-reward successes.",
    )
    parser.add_argument(
        "--extra-arg",
        action="append",
        default=[],
        help="Append one extra argument to the Harbor command. Repeat for multiple args.",
    )
    parser.add_argument(
        "--materials-only",
        action="store_true",
        help="Print just the material names that would be rerun.",
    )
    parser.add_argument(
        "--no-filtered-dataset",
        action="store_true",
        help="Print a command with --include-task-name filters instead of creating a filtered dataset.",
    )
    parser.add_argument(
        "--filtered-dataset-dir",
        type=Path,
        help="Directory to write the filtered symlink dataset. Defaults to a generated name next to --dataset.",
    )
    args = parser.parse_args()

    data = json.loads(args.summary.read_text(encoding="utf-8"))
    results = data.get("results")
    if not isinstance(results, list):
        raise SystemExit(f"{args.summary} does not contain a 'results' list")

    skip_materials: list[str] = []
    rerun_materials: list[str] = []
    for record in results:
        if not isinstance(record, dict):
            continue
        material = material_from_record(record)
        if is_positive_reward_success(record):
            skip_materials.append(material)
        else:
            rerun_materials.append(material)

    skip_materials = sorted(set(skip_materials))
    rerun_materials = sorted(set(rerun_materials))
    all_materials = dataset_materials(args.dataset)
    run_materials = (
        rerun_materials
        if args.previous_only
        else sorted(set(all_materials) - set(skip_materials))
    )

    if args.materials_only:
        print(" ".join(run_materials))
        return

    mode = "previous non-success/zero-reward tasks only" if args.previous_only else "all tasks except prior successes"
    run_dataset = args.dataset
    if not args.no_filtered_dataset:
        run_dataset = args.filtered_dataset_dir or filtered_dataset_dir(args, run_materials)
        materialize_filtered_dataset(args.dataset, run_dataset, run_materials)

    print(f"# Summary: {relpath_for_command(args.summary)}")
    print(f"# Mode: include {mode}")
    print(f"# Skipping {len(skip_materials)} prior tasks with status=success and reward>0.0")
    print(f"# Running {len(run_materials)} tasks")
    print(f"# Dataset: {relpath_for_command(run_dataset)}")

    if args.no_filtered_dataset:
        command = build_command(args, args.dataset)
        for material in run_materials:
            command.extend(["--include-task-name", f"wannier_200/{material}"])
    else:
        command = build_command(args, run_dataset)
    print(shlex.join(command))


if __name__ == "__main__":
    main()
