#!/usr/bin/env python3
"""Print a Harbor command that runs all tasks ordered by instruction num_wann."""

from __future__ import annotations

import argparse
import re
import shlex
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATASET = ROOT / "harbor_datasets" / "wannier_200"
NUM_WANN_RE = re.compile(r"\bnum_wann\s*=\s*(\d+)\b")


def relpath_for_command(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(Path.cwd().resolve()))
    except ValueError:
        return str(path)


def read_num_wann(task_dir: Path) -> int:
    instruction = task_dir / "instruction.md"
    if not instruction.exists():
        raise SystemExit(f"missing instruction.md: {instruction}")

    match = NUM_WANN_RE.search(instruction.read_text(encoding="utf-8"))
    if match is None:
        raise SystemExit(f"could not find 'num_wann = <int>' in {instruction}")
    return int(match.group(1))


def dataset_tasks(dataset: Path) -> list[tuple[int, str, Path]]:
    if not dataset.is_dir():
        raise SystemExit(f"dataset directory does not exist: {dataset}")

    tasks: list[tuple[int, str, Path]] = []
    for task_dir in sorted(path for path in dataset.iterdir() if path.is_dir()):
        material = task_dir.name
        tasks.append((read_num_wann(task_dir), material, task_dir))
    return sorted(tasks)


def ordered_dataset_dir(dataset: Path) -> Path:
    return dataset.parent / f"{dataset.name}__num_wann_ordered"


def materialize_ordered_dataset(source_dataset: Path, target_dataset: Path, tasks: list[tuple[int, str, Path]]) -> None:
    target_dataset.mkdir(parents=True, exist_ok=True)
    wanted_names = {
        f"{index:04d}__num_wann_{num_wann:03d}__{material}"
        for index, (num_wann, material, _task_dir) in enumerate(tasks, start=1)
    }

    for path in list(target_dataset.iterdir()):
        if path.name == "README.md":
            continue
        if path.name not in wanted_names and path.is_symlink():
            path.unlink()
        elif path.name not in wanted_names:
            raise SystemExit(
                f"Refusing to remove non-symlink path in generated dataset: {path}. "
                "Choose a different --ordered-dataset-dir."
            )

    for index, (num_wann, material, source) in enumerate(tasks, start=1):
        target = target_dataset / f"{index:04d}__num_wann_{num_wann:03d}__{material}"
        if target.exists() or target.is_symlink():
            if target.is_symlink() and target.resolve() == source.resolve():
                continue
            raise SystemExit(
                f"Refusing to overwrite existing generated dataset entry: {target}. "
                "Choose a different --ordered-dataset-dir."
            )
        target.symlink_to(source.resolve(), target_is_directory=True)

    lines = [
        "# Num-Wann Ordered Wannier 200 Harbor Dataset",
        "",
        f"Source dataset: `{source_dataset}`",
        f"Task count: {len(tasks)}",
        "",
        "Order:",
    ]
    lines.extend(
        f"{index}. `{material}`: `num_wann = {num_wann}`"
        for index, (num_wann, material, _source) in enumerate(tasks, start=1)
    )
    lines.extend(["", "Generated by `scripts/generate_harbor_num_wann_order_command.py`.", ""])
    (target_dataset / "README.md").write_text("\n".join(lines), encoding="utf-8")


def build_command(args: argparse.Namespace, dataset: Path) -> list[str]:
    command = [
        "harbor",
        "run",
        "-p",
        relpath_for_command(dataset),
        "-a",
        args.agent,
        "-m",
        args.model,
    ]

    if args.extra_arg:
        command.extend(args.extra_arg)

    return command


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Read every task's instruction.md, sort by num_wann ascending, "
            "and print a Harbor run command for all tasks in that order."
        )
    )
    parser.add_argument("--dataset", "-p", type=Path, default=DEFAULT_DATASET)
    parser.add_argument("--agent", "-a", default="gemini-cli")
    parser.add_argument("--model", "-m", default="google/gemini-3.1-pro-preview")
    parser.add_argument(
        "--extra-arg",
        action="append",
        default=[],
        help="Append one extra argument to the Harbor command. Repeat for multiple args.",
    )
    parser.add_argument(
        "--materials-only",
        action="store_true",
        help="Print just the material names in num_wann order.",
    )
    parser.add_argument(
        "--no-ordered-dataset",
        action="store_true",
        help="Print a command with --include-task-name filters instead of creating an ordered dataset.",
    )
    parser.add_argument(
        "--ordered-dataset-dir",
        type=Path,
        help="Directory to write the ordered symlink dataset. Defaults to a generated name next to --dataset.",
    )
    args = parser.parse_args()

    tasks = dataset_tasks(args.dataset)
    if args.materials_only:
        print(" ".join(material for _num_wann, material, _source in tasks))
        return

    if args.no_ordered_dataset:
        command = build_command(args, args.dataset)
        for _num_wann, material, _source in tasks:
            command.extend(["--include-task-name", f"wannier_200/{material}"])
        run_dataset = args.dataset
    else:
        run_dataset = args.ordered_dataset_dir or ordered_dataset_dir(args.dataset)
        materialize_ordered_dataset(args.dataset, run_dataset, tasks)
        command = build_command(args, run_dataset)

    print(f"# Mode: include all tasks sorted by instruction num_wann ascending")
    print(f"# Running {len(tasks)} tasks")
    print(f"# Smallest num_wann: {tasks[0][1]} ({tasks[0][0]})")
    print(f"# Largest num_wann: {tasks[-1][1]} ({tasks[-1][0]})")
    print(f"# Dataset: {relpath_for_command(run_dataset)}")
    print(shlex.join(command))


if __name__ == "__main__":
    main()
